### ISSUE TITLE
uninitialized constant Post::Comment

### ISSUE THREAD

**Issue by MelissaKaulfuss** [MelissaKaulfuss/MK-blog#1]
![screen shot 2014-03-01 at 7 57 47 pm](https://f.cloud.github.com/assets/2578287/2301030/9839c608-a11f-11e3-8f95-074332a27e8f.png)

**Comment by lengarvey** [comment]
If you closed this then maybe you figured it out. But you're missing a `Comment` model. Check out the guide section: "Adding comments". Because you already have a comments controller you don't need to generate a resource like it says in the guide. All you need is the model and the database migration.

A model is a Ruby object which helps Rails map from the database to Ruby code.
A database migration is some Ruby code which changes the structure of your database. In your case the database is SQLite, but it could be Postgres or some other database.

```
rails generate model Comment post:references body:text
```

then run

```
rake db:migrate
```

Hope that helps!

**Comment by MelissaKaulfuss** [comment]
Thanks Leonard! I have fixed that (Elle M helped me!)...
Then I subsequently broke something else :)

Appreciate your efforts, thanks!

On 8 March 2014 08:05, Leonard Garvey notifications@github.com wrote:

> If you closed this then maybe you figured it out. But you're missing a
> Comment model. Check out the guide section: "Adding comments". Because
> you already have a comments controller you don't need to generate a
> resource like it says in the guide. All you need is the model and the
> database migration.
> 
> A model is a Ruby object which helps Rails map from the database to Ruby
> code.
> A database migration is some Ruby code which changes the structure of your
> database. In your case the database is SQLite, but it could be Postgres or
> some other database.
> 
> rails generate model Comment post:references body:text
> 
> then run
> 
> rake db:migrate
> 
> Hope that helps!
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/MelissaKaulfuss/MK-blog/issues/1#issuecomment-37067498
> .

## 

Melissa Kaulfuss
Icelab

15-25 Keele St,
Collingwood VIC 3066

Level 3, 8-10 Hobart Pl
Canberra ACT 2601
Australia

03 9416 3198
0422 636 026
michael@icelab.com.au

**Comment by rhaxor** [comment]
Can you tell me how you fixed it?
